//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fourriere
    {
        public int Id_Fourriere { get; set; }
        public string Nom_Fourriere { get; set; }
        public int Login_Admin { get; set; }
    
        public virtual Administrateur Administrateur { get; set; }
    }
}
