//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Gestion_FourriereContext : DbContext
    {
        public Gestion_FourriereContext()
            : base("name=Gestion_FourriereContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Administrateur> Administrateurs { get; set; }
        public virtual DbSet<Agent> Agents { get; set; }
        public virtual DbSet<Fourriere> Fourrieres { get; set; }
        public virtual DbSet<Montant> Montants { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Vehicule> Vehicules { get; set; }
    }
}
