//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicule
    {
        public string Immatriculation { get; set; }
        public string Marque { get; set; }
        public System.DateTime Date_entree { get; set; }
        public Nullable<System.DateTime> Date_Sortiee { get; set; }
        public string Num_carte_grise { get; set; }
        public string Nom_Prenom_Proprietaire { get; set; }
        public Nullable<int> CIN_Conducteur { get; set; }
        public Nullable<double> Prix { get; set; }
        public string Nom_Fourriere { get; set; }
        public Nullable<int> Login_Agent { get; set; }
    
        public virtual Agent Agent { get; set; }
    }
}
